descope/.github

- .github/actions/docker/build/action.yml
> fix action syntax

- .github/actions/python/poetry/publish/action.yml
- .github/actions/python/poetry/setup/action.yml
Poetry publish
Python version input
> Python enhacements

- .github/actions/python/poetry/publish/action.yml
**_Disclaimer_**: This does not actually fix my fat fingers.
> fix: fat fingers

- .github/actions/python/poetry/publish/action.yml
As promised, fat fingers not fixed.
> Fix: Text if syntax

- .github/actions/python/poetry/publish/action.yml
so turns out you can't just override the default, if we want optional test we either make the whole action more complicated or just set it to prod, then override to test if needed 🤷
> fix: override with test

- .github/settings.yml
Adding required checks to settings
> chore: add required tests

- .github/settings.yml
> remove test enforcement

- .github/settings.yml
related to https://github.com/descope/etc/issues/760
> fix status checks

- .github/actions/python/poetry/setup/action.yml
> chore(poetry): ensure lockfile is valid

- profile/README.md
> added learning center articles

- profile/README.md
> swapped KB and Docs

- profile/README.md
> Added Followers tag

- profile/README.md
> Added additional frameworks

- profile/README.md
> Added Passport.js reference

- .github/actions/python/poetry/setup/action.yml
Remove Python cache to support action o self-hosted runners
> Remove Cache

- profile/README.md
> Added Java SDK reference

- .github/actions/docker/build/action.yml
- .github/actions/docker/metadata/action.yml
Related to https://github.com/descope/etc/issues/3427
Required for https://github.com/descope/auth-hosting/pull/38
1. Add a docker metadata action
2. Consume it in docker action
> Shared docker metadata action

- profile/README.md
> Added Angular and Retool

- profile/README.md
> Added Okta Integration

- profile/README.md
> Change Okta link

- profile/README.md
> Included mobile SDKs

- profile/README.md
> Added Angular to README

- profile/README.md
The [repo](https://github.com/descope/descopecli) will be made public in a few hours
> Add descopecli

- profile/README.md
> Update vue sdk url

- profile/README.md
Fixed links pointing to our old docs
> fixed broken links

- .github/actions/docker/metadata/action.yml
> fix(ci) - add branch name on pr

- .github/actions/docker/build/action.yml
Disable caching to allow CI process to pass.
> fix(ci) - disable cache for building process

- .github/actions/docker/build/action.yml
> fix(ci) - add extra step to allow job to pass

- profile/README.md
Updated old URL in the README.
> Updated Okta Redirect Url

- .github/actions/docker/build/action.yml
> fix(ci) - remove all the mess that are not in use

- profile/README.md
Fixes https://github.com/descope/etc/issues/11657
Update README with AI Content
> Update README.md with AI
